// Field Types
export const GROUP_FIELD_TYPE = 'group';
export type GROUP_FIELD_TYPE = typeof GROUP_FIELD_TYPE;
export const REPEAT_FIELD_TYPE = 'repeat';
export type REPEAT_FIELD_TYPE = typeof REPEAT_FIELD_TYPE;
export const TEXT_FIELD_TYPE = 'text';
export type TEXT_FIELD_TYPE = typeof TEXT_FIELD_TYPE;
export const DATE_FIELD_TYPE = 'date';
export type DATE_FIELD_TYPE = typeof DATE_FIELD_TYPE;
export const DATE_TIME_FIELD_TYPE = 'dateTime';
export type TIME_FIELD_TYPE = typeof TIME_FIELD_TYPE;
export const TIME_FIELD_TYPE = 'time';
export type DATE_TIME_FIELD_TYPE = typeof DATE_TIME_FIELD_TYPE;
export const INTEGER_FIELD_TYPE = 'integer';
export type INTEGER_FIELD_TYPE = typeof INTEGER_FIELD_TYPE;
export const DECIMAL_FIELD_TYPE = 'decimal';
export type DECIMAL_FIELD_TYPE = typeof DECIMAL_FIELD_TYPE;
export const PHOTO_FIELD_TYPE = 'photo';
export type PHOTO_FIELD_TYPE = typeof PHOTO_FIELD_TYPE;
export const FILE_FIELD_TYPE = 'file';
export type FILE_FIELD_TYPE = typeof FILE_FIELD_TYPE;
export const NOTE_FIELD_TYPE = 'note';
export type NOTE_FIELD_TYPE = typeof NOTE_FIELD_TYPE;
export const SELECT_ONE_FIELD_TYPE = 'select one';
export type SELECT_ONE_FIELD_TYPE = typeof SELECT_ONE_FIELD_TYPE;
export const SELECT_ALL_FIELD_TYPE = 'select all that apply';
export type SELECT_ALL_FIELD_TYPE = typeof SELECT_ALL_FIELD_TYPE;
export const CALCULATE_FIELD_TYPE = 'calculate';
export type CALCULATE_FIELD_TYPE = typeof CALCULATE_FIELD_TYPE;
export const GPS_FIELD_TYPE = 'gps';
export type GPS_FIELD_TYPE = typeof GPS_FIELD_TYPE;
export const AUDIO_FIELD_TYPE = 'audio';
export type AUDIO_FIELD_TYPE = typeof GPS_FIELD_TYPE;

// Required Properties
export const REQUIRED_FIELD_MSG = 'This field is required';
export type REQUIRED_FIELD_MSG = typeof REQUIRED_FIELD_MSG;
export const REQUIRED_SYMBOL = '*';
export type REQUIRED_SYMBOL = typeof REQUIRED_SYMBOL;
